"""Assemble the generated stub module (and the README) from a workset."""

from __future__ import annotations

from ..model import (
    Projection,
    _auto_name,  # pyright: ignore[reportPrivateUsage] — intra-package
)
from .config import CodegenError, Config
from .discover import (
    _build_workset,
    _discover,
    _Plan,  # pyright: ignore[reportPrivateUsage] — intra-package
)
from .render import (
    _field_suffix,
    _import_lines,
    _Imports,
    _render_annotation,
    _render_scope_expr,
    _render_type_ref,
)

__all__ = ["generate", "generate_readme"]

_BANNER = (
    "# This file is generated by `prism gen` — do not edit by hand.\n"
    "# Regenerate after changing scoped models; `prism check` verifies it.\n"
    "# ruff: noqa  (generated; kept exactly as `prism gen` emits it)\n"
)


def generate_readme(config: Config) -> str:
    """Render the GitHub README documenting ``config``'s generated workset."""
    from ..readme import build_readme

    projections, _ = _build_workset(_discover(config))
    if not projections:
        raise CodegenError(
            "no projections to document — the configured modules define no "
            "scoped models with tagged fields"
        )
    return build_readme(projections)


def generate(config: Config) -> str:
    """Render the full generated module for ``config`` as a string."""
    plans = _discover(config)
    projections, directives = _build_workset(plans)
    if not projections:
        raise CodegenError(
            "no projections to generate — the configured modules define no "
            "scoped models with tagged fields"
        )

    imports = _Imports()
    imports.add_typing("pydantic_prism", "Projection")

    class_blocks: list[str] = []
    alias_lines: list[str] = []

    for proj in projections:
        class_blocks.append(_render_class(proj, imports))
        alias_lines.append(_render_alias(proj, imports, directives.get(proj)))

    out: list[str] = [
        _BANNER.rstrip("\n"),
        "",
        "from __future__ import annotations",
        "",
    ]
    out.append("from typing import TYPE_CHECKING")
    out.append("")
    out.extend(_import_lines(imports.runtime, "", imports.bound))
    out.append("")
    out.append("if TYPE_CHECKING:")
    out.extend(_import_lines(imports.typing_only, "    ", imports.bound))
    out.append("")
    out.append("\n\n".join(class_blocks))
    out.append("else:")
    out.extend(f"    {line}" for line in alias_lines)
    out.append("")
    return "\n".join(out) + "\n"


def _render_class(proj: type[Projection], imports: _Imports) -> str:
    base_names = [_render_type_ref(base, imports) for base in proj.__prism__.bases]
    bases = ", ".join([*base_names, "Projection"])
    lines = [f"    class {proj.__name__}({bases}):"]
    for name, info in proj.model_fields.items():
        annotation = _render_annotation(info.annotation, imports)
        lines.append(f"        {name}: {annotation}{_field_suffix(info, imports)}")
        # Preserve the field's description as an attribute docstring — surfaced
        # by pyright/Pylance on hover; the runtime object carries the real one.
        if info.description:
            lines.append(f"        {info.description!r}")
    return "\n".join(lines)


def _render_alias(proj: type[Projection], imports: _Imports, plan: _Plan | None) -> str:
    source = proj.__prism__.source
    source_ref = imports.add_runtime(source.__module__, source.__qualname__)
    if plan is not None and plan.kind != "scope":
        return _render_directional_alias(proj, source_ref, plan, imports)
    expr_src = _render_scope_expr(proj.__prism__.scope, imports)
    auto_name = _auto_name(source, proj.__prism__.scope)
    if proj.__name__ == auto_name:
        return f"{proj.__name__} = {source_ref}.scope({expr_src})"
    return f"{proj.__name__} = {source_ref}.scope({expr_src}, name={proj.__name__!r})"


def _render_directional_alias(
    proj: type[Projection], source_ref: str, plan: _Plan, imports: _Imports
) -> str:
    """Render an ``.input()`` / ``.output()`` runtime alias from its plan.

    ``plan.expr`` is the *visible* scope (the method subtracts ``Out`` / ``In``).
    ``name=`` and ``extra=`` are emitted only when they differ from the runtime
    helper's own defaults (``"{Model}In"`` / ``"{Model}Out"``; ``"forbid"``).
    """
    args = [_render_scope_expr(plan.expr, imports)]
    suffix = "In" if plan.kind == "input" else "Out"
    if proj.__name__ != f"{plan.source.__name__}{suffix}":
        args.append(f"name={proj.__name__!r}")
    if plan.kind == "input" and plan.extra is not None and plan.extra != "forbid":
        args.append(f"extra={plan.extra!r}")
    return f"{proj.__name__} = {source_ref}.{plan.kind}({', '.join(args)})"
