"""Generate a GitHub-flavoured README for ``pydantic-prism gen``-reflected models.

GitHub renders ```mermaid fenced blocks inline, so the generated doc ships with
visible diagrams (scope hierarchy, per-model projection fan-out, relationship
graph) plus per-projection field tables (name / type / description). It
documents exactly the generated workset, grouped by source canonical model.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Sequence
from typing import TYPE_CHECKING

from ..diagram import (
    _node_fields,  # pyright: ignore[reportPrivateUsage] — intra-package
    projection_diagram,
    scope_diagram,
)

if TYPE_CHECKING:
    from .model import Projection, ScopedModel
    from .scopes import Scope

__all__ = ["build_readme"]


def _cell(text: str) -> str:
    """Escape a value for a Markdown table cell."""
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ")


def _fenced_mermaid(body: str) -> list[str]:
    return ["```mermaid", body.rstrip("\n"), "```", ""]


def build_readme(
    projections: Sequence[type[Projection]], *, regen_hint: str = "pydantic-prism gen"
) -> str:
    """Render the GitHub README for a generated projection workset.

    ``regen_hint`` is the command shown in the do-not-edit banner
    (``pydantic-prism gen`` for stub generation, or whatever script produced the
    file).
    """
    by_source: dict[type[ScopedModel], list[type[Projection]]] = defaultdict(list)
    for proj in projections:
        by_source[proj.__prism__.source].append(proj)
    sources = sorted(by_source, key=lambda cls: cls.__name__)

    banner = (
        f"<!-- generated by `{regen_hint}` — do not edit; "
        f"regenerate with `{regen_hint}` -->"
    )
    lines = ["# Generated projection models", "", banner, ""]

    all_scopes: set[type[Scope]] = set()
    for source in sources:
        all_scopes |= set(source.scopes())
    if all_scopes:
        ordered = sorted(all_scopes, key=lambda scope: scope.__name__)
        lines += ["## Scopes", ""]
        lines += _fenced_mermaid(scope_diagram(*ordered).to_mermaid())

    for source in sources:
        lines.append(f"## {source.__name__}")
        if source.__doc__:
            lines += ["", source.__doc__.strip()]
        lines.append("")
        lines += _fenced_mermaid(projection_diagram(source).to_mermaid())
        for proj in sorted(by_source[source], key=lambda cls: cls.__name__):
            token = proj.__prism__.scope.token()
            lines.append(f"### {proj.__name__} — scope `{token}`")
            lines += ["", "| field | type | description |", "|---|---|---|"]
            for node_field in _node_fields(proj):
                lines.append(
                    f"| {_cell(node_field.name)} | {_cell(node_field.type or '')} "
                    f"| {_cell(node_field.description or '')} |"
                )
            lines.append("")
        refs = source.__prism__.refs.diagram()
        if refs.edges:  # only when there's a forward edge to show
            lines.append(f"### {source.__name__} relationships")
            lines.append("")
            lines += _fenced_mermaid(refs.to_mermaid())

    return "\n".join(lines).rstrip("\n") + "\n"
