"""``prism gen`` / ``prism check`` — generate static-typing stubs for projections.

Static type checkers (pyright/Pylance — and thus VSCode — plus mypy) cannot see
the fields of ``Model.scope(...)``: scope membership lives in ``Annotated``
metadata and the selection runs the scope algebra at runtime. Pyright has no
third-party plugin API, so the only *universal* fix is ordinary type
declarations every tool already reads. This module generates them.

For each projection it emits, into one module::

    if TYPE_CHECKING:
        class ScreenshotRef(Projection):     # the checker reads this
            id: UUID
            timestamp: datetime
    else:
        ScreenshotRef = Screenshot.scope(Ref)   # the genuine cached projection

    assert_fresh(ScreenshotRef, "<signature>")   # startup drift guard

The ``TYPE_CHECKING`` class is the typing surface; the runtime object is the
authentic ``.scope()`` result (so validators, refs, carried bases, partial
defaults, FastAPI ``response_model=`` all work and
``ScreenshotRef is Screenshot.scope(Ref)``). :func:`assert_fresh` re-checks the
signature at import; ``prism check`` compares freshly generated output to the
file on disk as a non-importing CI gate.
"""

from __future__ import annotations

import argparse
import enum
import importlib
import sys
import tomllib
import types
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, Union, cast, get_args, get_origin

from ._drift import projection_signature
from ._model import (
    Projection,
    ScopedModel,
    _auto_name,  # pyright: ignore[reportPrivateUsage] — intra-package
)
from ._scopes import (
    ScopeExpr,
    _Atom,  # pyright: ignore[reportPrivateUsage] — intra-package expr rendering
    _Complement,  # pyright: ignore[reportPrivateUsage]
    _Difference,  # pyright: ignore[reportPrivateUsage]
    _Intersection,  # pyright: ignore[reportPrivateUsage]
    _Union,  # pyright: ignore[reportPrivateUsage]
    as_expr,
    union_all,
)

__all__ = ["CodegenError", "Config", "ProjectionSpec", "generate", "main"]

_BANNER = (
    "# This file is generated by `prism gen` — do not edit by hand.\n"
    "# Regenerate after changing scoped models; `prism check` verifies it.\n"
    "# ruff: noqa  (generated; kept exactly as `prism gen` emits it)\n"
)


class CodegenError(Exception):
    """A stub-generation request could not be fulfilled (bad config or input)."""


@dataclass(frozen=True)
class ProjectionSpec:
    """One opt-in projection beyond a model's per-atom defaults.

    ``model`` and each ``scopes`` entry are ``"package.module:Name"`` paths; the
    scopes union together (like ``scoped(A, B)`` / ``.scope(A, B)``).
    """

    model: str
    scopes: tuple[str, ...]
    name: str | None = None


@dataclass(frozen=True)
class Config:
    """Resolved ``[tool.pydantic-prism]`` configuration."""

    output: Path
    modules: tuple[str, ...]
    projections: tuple[ProjectionSpec, ...]
    root: Path


# --- configuration ---------------------------------------------------------


def load_config(pyproject: Path) -> Config:
    """Read ``[tool.pydantic-prism]`` from a ``pyproject.toml``."""
    with pyproject.open("rb") as handle:
        data = tomllib.load(handle)
    table = data.get("tool", {}).get("pydantic-prism")
    if not isinstance(table, dict):
        raise CodegenError(
            f"{pyproject}: no [tool.pydantic-prism] table; add one with an "
            f"`output` path and `modules` to scan"
        )
    table = cast(dict[str, Any], table)
    output = table.get("output")
    if not isinstance(output, str):
        raise CodegenError(
            f"{pyproject}: [tool.pydantic-prism] needs a string `output` path"
        )
    modules = tuple(cast(Sequence[str], table.get("modules", [])))
    raw_projections = cast(Sequence[Any], table.get("projections", []))
    projections = tuple(_parse_spec(entry, pyproject) for entry in raw_projections)
    if not modules and not projections:
        raise CodegenError(
            f"{pyproject}: [tool.pydantic-prism] selects nothing — set `modules` "
            f"and/or `projections`"
        )
    root = pyproject.resolve().parent
    return Config(
        output=root / output,
        modules=modules,
        projections=projections,
        root=root,
    )


def _parse_spec(entry: Any, pyproject: Path) -> ProjectionSpec:
    if not isinstance(entry, dict):
        raise CodegenError(
            f"{pyproject}: each [[tool.pydantic-prism.projections]] "
            f"entry must be a table, got {entry!r}"
        )
    entry = cast(dict[str, Any], entry)
    model = entry.get("model")
    scopes = entry.get("scopes")
    name = entry.get("name")
    if not isinstance(model, str):
        raise CodegenError(f"{pyproject}: a projections entry needs a string `model`")
    scope_list = cast(list[Any], scopes) if isinstance(scopes, list) else []
    if not scope_list or not all(isinstance(s, str) for s in scope_list):
        raise CodegenError(
            f"{pyproject}: projections entry for {model!r} needs a non-empty "
            f"`scopes` list of 'module:Name' strings"
        )
    if name is not None and not isinstance(name, str):
        raise CodegenError(
            f"{pyproject}: projections `name` for {model!r} must be a string"
        )
    return ProjectionSpec(
        model=model, scopes=tuple(cast(list[str], scope_list)), name=name
    )


# --- discovery -------------------------------------------------------------


@dataclass
class _Plan:
    source: type[ScopedModel]
    expr: ScopeExpr
    name: str | None


def _resolve(path: str) -> Any:
    module_name, sep, attr = path.partition(":")
    if not sep or not attr:
        raise CodegenError(f"{path!r}: expected a 'package.module:Name' path")
    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:  # noqa: F841 — message includes the path
        raise CodegenError(f"{path!r}: cannot import module {module_name!r}") from exc
    try:
        return getattr(module, attr)
    except AttributeError as exc:
        raise CodegenError(
            f"{path!r}: {module_name!r} has no attribute {attr!r}"
        ) from exc


def _discover(config: Config) -> list[_Plan]:
    """The (model, scope-expression, name) triples to generate, deduplicated."""
    if str(config.root) not in sys.path:
        sys.path.insert(0, str(config.root))
    plans: dict[tuple[type[ScopedModel], ScopeExpr, str | None], _Plan] = {}

    def add(source: type[ScopedModel], expr: ScopeExpr, name: str | None) -> None:
        plans.setdefault((source, expr, name), _Plan(source, expr, name))

    for module_name in config.modules:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                isinstance(obj, type)
                and issubclass(obj, ScopedModel)
                and obj is not ScopedModel
                and obj.__module__ == module_name
            ):
                for scope in sorted(obj.scopes(), key=lambda s: s.__name__):
                    add(obj, as_expr(scope), None)

    for spec in config.projections:
        source = _resolve(spec.model)
        if not (isinstance(source, type) and issubclass(source, ScopedModel)):
            raise CodegenError(f"{spec.model!r} is not a ScopedModel subclass")
        expr = union_all(as_expr(_resolve(path)) for path in spec.scopes)
        add(source, expr, spec.name)

    return list(plans.values())


def _build_workset(plans: Sequence[_Plan]) -> list[type[Projection]]:
    """Build planned projections and every nested projection they reference."""
    workset: dict[type[Projection], None] = {}
    for plan in plans:
        built = plan.source.scope(plan.expr, name=plan.name)
        _collect(built, workset)
    ordered = sorted(workset, key=lambda p: p.__name__)
    _reject_name_clashes(ordered)
    return ordered


def _collect(proj: type[Projection], workset: dict[type[Projection], None]) -> None:
    if proj in workset:
        return
    workset[proj] = None
    for info in proj.model_fields.values():
        for nested in _projections_in(info.annotation):
            _collect(nested, workset)


def _reject_name_clashes(projections: Sequence[type[Projection]]) -> None:
    seen: dict[str, type[Projection]] = {}
    for proj in projections:
        other = seen.get(proj.__name__)
        if other is not None and other is not proj:
            raise CodegenError(
                f"two projections share the generated name {proj.__name__!r} "
                f"(of {other.__prism_source__.__name__} and "
                f"{proj.__prism_source__.__name__}); pass a distinct name= via a "
                f"projections entry"
            )
        seen[proj.__name__] = proj


def _projections_in(annotation: Any) -> list[type[Projection]]:
    found: list[type[Projection]] = []
    _walk_projections(annotation, found)
    return found


def _walk_projections(annotation: Any, out: list[type[Projection]]) -> None:
    while hasattr(annotation, "__metadata__"):
        annotation = get_args(annotation)[0]
    if isinstance(annotation, type):
        if issubclass(annotation, Projection) and annotation is not Projection:
            out.append(annotation)
        return
    for arg in get_args(annotation):
        if isinstance(arg, list):  # Callable parameter lists
            for item in cast(list[Any], arg):
                _walk_projections(item, out)
        else:
            _walk_projections(arg, out)


# --- import bookkeeping ----------------------------------------------------


def _empty_import_set() -> set[tuple[str, str]]:
    return set()


@dataclass
class _Imports:
    runtime: set[tuple[str, str]] = field(default_factory=_empty_import_set)
    typing_only: set[tuple[str, str]] = field(default_factory=_empty_import_set)

    def add_runtime(self, module: str, name: str) -> None:
        self.runtime.add((module, name))

    def add_typing(self, module: str, name: str) -> None:
        self.typing_only.add((module, name))


def _import_lines(pairs: set[tuple[str, str]], indent: str) -> list[str]:
    by_module: dict[str, set[str]] = {}
    for module, name in pairs:
        by_module.setdefault(module, set()).add(name)
    return [
        f"{indent}from {module} import {', '.join(sorted(by_module[module]))}"
        for module in sorted(by_module)
    ]


# --- annotation rendering --------------------------------------------------


def _render_annotation(annotation: Any, imports: _Imports) -> str:
    while hasattr(annotation, "__metadata__"):  # strip Annotated (typing only)
        annotation = get_args(annotation)[0]
    if annotation is None or annotation is types.NoneType:
        return "None"
    origin = get_origin(annotation)
    if origin is None:
        return _render_bare(annotation, imports)
    if origin is Union or origin is types.UnionType:
        return " | ".join(_render_annotation(a, imports) for a in get_args(annotation))
    if origin is Literal:
        rendered = ", ".join(_render_literal(v, imports) for v in get_args(annotation))
        imports.add_typing("typing", "Literal")
        return f"Literal[{rendered}]"
    name = _render_type_ref(origin, imports)
    args = get_args(annotation)
    parts = [
        "..." if arg is Ellipsis else _render_annotation(arg, imports) for arg in args
    ]
    return f"{name}[{', '.join(parts)}]"


def _render_bare(annotation: Any, imports: _Imports) -> str:
    if annotation is Any:
        imports.add_typing("typing", "Any")
        return "Any"
    if isinstance(annotation, type):
        return _render_type_ref(annotation, imports)
    raise CodegenError(
        f"cannot render annotation {annotation!r} to source; only concrete "
        f"types, unions, Optional, Literal, and standard containers are supported"
    )


def _render_type_ref(tp: type[Any], imports: _Imports) -> str:
    if issubclass(tp, Projection) and tp is not Projection:
        return tp.__name__  # sibling stub class; forward-referenced by name
    module = tp.__module__
    qualname = tp.__qualname__
    if module == "builtins":
        return qualname
    imports.add_typing(module, qualname.split(".")[0])
    return qualname


def _render_literal(value: Any, imports: _Imports) -> str:
    if value is None:
        return "None"
    if isinstance(value, enum.Enum):
        cls = type(value)
        imports.add_typing(cls.__module__, cls.__qualname__.split(".")[0])
        return f"{cls.__qualname__}.{value.name}"
    if isinstance(value, (bool, int, float, str, bytes)):
        return repr(value)
    raise CodegenError(f"cannot render Literal value {value!r} to source")


# --- scope-expression rendering --------------------------------------------


def _render_scope_expr(expr: ScopeExpr, imports: _Imports) -> str:
    if isinstance(expr, _Atom):
        scope = expr.scope
        imports.add_runtime(scope.__module__, scope.__qualname__.split(".")[0])
        return scope.__qualname__
    if isinstance(expr, _Union):
        return (
            "("
            + " | ".join(_render_scope_expr(o, imports) for o in expr.operands)
            + ")"
        )
    if isinstance(expr, _Intersection):
        return (
            "("
            + " & ".join(_render_scope_expr(o, imports) for o in expr.operands)
            + ")"
        )
    if isinstance(expr, _Difference):
        left = _render_scope_expr(expr.left, imports)
        right = _render_scope_expr(expr.right, imports)
        return f"({left} - {right})"
    if isinstance(expr, _Complement):
        return f"~{_render_scope_expr(expr.operand, imports)}"
    raise CodegenError(f"cannot render scope expression {expr!r} to source")


# --- field rendering -------------------------------------------------------

_FACTORIES: tuple[type[Any], ...] = (list, dict, set, frozenset, tuple)


def _field_suffix(info: Any, imports: _Imports) -> str:
    """The ``= default`` tail for a stub field, type-correct or omitted.

    Required fields get nothing. Optional fields are made optional in the
    synthesized constructor only when the default renders cleanly (``None``, a
    simple literal, or a known builtin ``default_factory``); anything exotic is
    left looking required — the runtime object is authoritative, so this only
    makes the stub's constructor conservative, never wrong.
    """
    if info.is_required():
        return ""
    if info.default_factory is not None:
        for factory in _FACTORIES:
            if info.default_factory is factory:
                imports.add_typing("pydantic", "Field")
                return f" = Field(default_factory={factory.__name__})"
        return ""
    default = info.default
    if default is None:
        return " = None"
    if isinstance(default, (bool, int, float, str, bytes)):
        return f" = {default!r}"
    return ""


# --- assembly --------------------------------------------------------------


def generate(config: Config) -> str:
    """Render the full generated module for ``config`` as a string."""
    plans = _discover(config)
    projections = _build_workset(plans)
    if not projections:
        raise CodegenError(
            "no projections to generate — the configured modules define no "
            "scoped models with tagged fields"
        )

    imports = _Imports()
    imports.runtime.add(("pydantic_prism._drift", "assert_fresh"))
    imports.add_typing("pydantic_prism", "Projection")

    class_blocks: list[str] = []
    alias_lines: list[str] = []
    assert_lines: list[str] = []

    for proj in projections:
        class_blocks.append(_render_class(proj, imports))
        alias_lines.append(_render_alias(proj, imports))
        assert_lines.append(
            f'assert_fresh({proj.__name__}, "{projection_signature(proj)}")'
        )

    out: list[str] = [
        _BANNER.rstrip("\n"),
        "",
        "from __future__ import annotations",
        "",
    ]
    out.append("from typing import TYPE_CHECKING")
    out.append("")
    out.extend(_import_lines(imports.runtime, ""))
    out.append("")
    out.append("if TYPE_CHECKING:")
    out.extend(_import_lines(imports.typing_only, "    "))
    out.append("")
    out.append("\n\n".join(class_blocks))
    out.append("else:")
    out.extend(f"    {line}" for line in alias_lines)
    out.append("")
    out.extend(assert_lines)
    return "\n".join(out) + "\n"


def _render_class(proj: type[Projection], imports: _Imports) -> str:
    base_names = [_render_type_ref(base, imports) for base in proj.__prism_bases__]
    bases = ", ".join([*base_names, "Projection"])
    lines = [f"    class {proj.__name__}({bases}):"]
    for name, info in proj.model_fields.items():
        annotation = _render_annotation(info.annotation, imports)
        lines.append(f"        {name}: {annotation}{_field_suffix(info, imports)}")
        # Preserve the field's description as an attribute docstring — surfaced
        # by pyright/Pylance on hover; the runtime object carries the real one.
        if info.description:
            lines.append(f"        {info.description!r}")
    return "\n".join(lines)


def _render_alias(proj: type[Projection], imports: _Imports) -> str:
    source = proj.__prism_source__
    imports.add_runtime(source.__module__, source.__qualname__.split(".")[0])
    expr_src = _render_scope_expr(proj.__prism_scope__, imports)
    auto_name = _auto_name(source, proj.__prism_scope__)
    if proj.__name__ == auto_name:
        return f"{proj.__name__} = {source.__name__}.scope({expr_src})"
    return (
        f"{proj.__name__} = {source.__name__}.scope({expr_src}, name={proj.__name__!r})"
    )


# --- CLI -------------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="prism", description="Generate static-typing stubs for prism projections."
    )
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("gen", "check"):
        p = sub.add_parser(command)
        p.add_argument(
            "--config", default="pyproject.toml", help="path to pyproject.toml"
        )
    args = parser.parse_args(argv)
    try:
        config = load_config(Path(args.config))
        text = generate(config)
    except (CodegenError, OSError) as exc:
        print(f"prism: {exc}", file=sys.stderr)
        return 2
    if args.command == "gen":
        config.output.write_text(text, encoding="utf-8")
        count = text.count("assert_fresh(")
        print(f"prism: wrote {count} projection stub(s) to {config.output}")
        return 0
    existing = (
        config.output.read_text(encoding="utf-8") if config.output.exists() else None
    )
    if existing != text:
        print(
            f"prism: {config.output} is out of date — run `prism gen`",
            file=sys.stderr,
        )
        return 1
    print(f"prism: {config.output} is up to date")
    return 0
